### ISSUE TITLE
Correção de bug - 

### ISSUE THREAD

**Issue by screstani** [screstani/projeto-final-git#2]
Correção de bug - redirecionamento na página inicial para o link da calculadora está quebrado, conforme mensagem abaixo: Cannot GET /calculatr.html

**Comment by LeonardoDuct** [comment]
Foi verificado que esse erro estava sendo causado pois a rota para fazer o redirecionamento para a aplicação não estava correta.
O erro foi corrigido fazendo a indicação da rota da calculadora nos demais arquivos HTML.

**Comment by screstani** [comment]
Issue reaberta por engano, solução já verificada e ok.
